version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  api:
    build:
      context: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - mongodb
    ports:
      - "8000:8000"